# Nombre de la aplicación
spring.application.name=Bookings_App

# Configuración de la base de datos
spring.datasource.url=jdbc:mysql://localhost:3306/bookings_app
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Puerto del servidor
server.port=8080

# Codificación por defecto
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# Ruta por defecto de inicio
spring.mvc.view.prefix=/templates/
spring.mvc.view.suffix=.html
